### Default
GET http://localhost:3001/

### GET all persons
GET http://localhost:3001/api/persons/

### Get single person
GET http://localhost:3001/api/persons/400

### Get single person
GET http://localhost:3001/api/persons/600d6f129c7c14271ca07713

### Delete single person
DELETE http://localhost:3001/api/persons/3

### Delete single person
DELETE http://localhost:3001/api/persons/600d6f129c7c14271ca07713

### POST new Data
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Nishant",
    "number": 9876543210
}