### Default
GET http://localhost:3001/

### Info
GET http://localhost:3001/info/

### GET all persons
GET http://localhost:3001/api/persons/

### Get single person
GET http://localhost:3001/api/persons/

### Delete single person
DELETE http://localhost:3001/api/persons/3

### POST a note
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Nishant",
    "number": 9876543210
}